server:
  port: 8001

spring:
  application:
    name: buyer-service
  datasource:
    url: jdbc:mysql://localhost:3306/emart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
  main:
    allow-bean-definition-overriding: true
app-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
