eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 15
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8989
spring:
  application:
    name: zuul-server
  main:
    banner-mode: off
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
#  servlet-path: /
  routes:
    buyer-service:
      path: /buyer-service/**
      service-id: app-buyer
      strip-prefix: false
    seller-service:
      path: /seller-service/**
      service-id: app-seller
      strip-prefix: false
    user-service:
      path: /user-service/**
      service-id: app-user
      strip-prefix: false

